### PR TITLE
(#71) port backend sopht code

### LINKED ISSUE #71: Port backend code from sopht-backend

### PR DESCRIPTION
**Pull request by bhosale2**
Fixes #71.

### CODE REVIEW

**Review by armantekinalp — APPROVED** [review]
LGTM

**Comment by bhosale2** [comment]
@fankiat as you can see from this PR, we are merging the backend here (with the code structure the same and kept in `sopht` folder), and for backend-compatibility will keep the `sopht-backend` repo as it is. However, the `sopht` on this repo will be kept up to date, and I would recommend to update `sopht-mpi` to include this repo as the actual dependency instead of `backend`.

**Comment by fankiat** [comment]
> @fankiat as you can see from this PR, we are merging the backend here (with the code structure the same and kept in `sopht` folder), and for backend-compatibility will keep the `sopht-backend` repo as it is. However, the `sopht` on this repo will be kept up to date, and I would recommend to update `sopht-mpi` to include this repo as the actual dependency instead of `backend`.

@bhosale2 sorry for the delayed response and thanks for keeping me updated. I can work on this today probably on `sopht-mpi`. Just for me to understand and probably learn the thought process here, what's the rationale for porting the backend here? Thanks!

**Comment by bhosale2** [comment]
@fankiat it is easier to maintain and develop the numerics and simulator code at the same place, especially when there are plans to add more numerical features to `sopht`. Specifically, in the upcoming months, there are plans to add more numerical features to speed up things and add expand functionalities. Separating the `backend` at the start itself was not in my opinion the best decision.

Ideally, `sopht-mpi` should also be part of this repo for easier maintenance, however, allowing different installable versions (non-`mpi` and `mpi`) would require some complicated steps to be figured out (from `poetry` side).  For now, just setting this repo as a dependency should be sufficient, since all backend features will be available under the `sopht` module, just as before. In the future, we can revisit the idea of having one repo.

**Comment by fankiat** [comment]
@bhosale2 i see. yeah I also think `backend` should not be separated as a different repo. Maintaing and adding new features is definitely cumblesome. Looking forward to the new numerical features and FSI functionalities, and let me know if there is anything you think I can be of help.

And yes, ideally `sopht-mpi` should aos be part of this repo, but we will figure that out later when we have the repo working fully and porting them here should not be an issue (except maybe the poetry side of things). I'll set this repo as dependency for `sopht-mpi` for now as suggested.

**Pull request merged**
